# aa-enabled
# Autogenerated from man page /usr/lib/jvm/default/man/man1/aa-enabled.1.gz
complete -c aa-enabled -s h -l help -d 'Display a brief usage guide'
complete -c aa-enabled -s q -l quiet -d 'Do not output anything to stdout'

