# avifix
# Autogenerated from man page /usr/lib/jvm/default/man/man1/avifix.1.gz
complete -c avifix -s i -d 'Specify the name of the AVI-file'
complete -c avifix -s F -d 'Specify the video codec as FourCC. br Possible values are RGB, RIFF and TIFF'
complete -c avifix -s f -d 'Use this option to change the frame rate and scale information in the header …'
complete -c avifix -s N -d 'Use this option to change the audio format identifier in the header of the AV…'
complete -c avifix -s b -d 'Use this option to change the encoder bitrate in the header of the AVI-file'
complete -c avifix -s e -d 'Use this option to change the audio stream parameters of in the header of the…'
complete -c avifix -s a -d 'Use this option to change the audio stream parameters of audio track number n…'
complete -c avifix -s v -d 'Print version information and exit.  EXAMPLES The command'

