# aviindex
# Autogenerated from man page /usr/lib/jvm/default/man/man1/aviindex.1.gz
complete -c aviindex -s o -d 'Specify the name of the output file'
complete -c aviindex -s i -d 'Specify the name of the input file'
complete -c aviindex -s f -d 'force the use of the existing index'
complete -c aviindex -s n -d 'force generating the index by scanning the file'
complete -c aviindex -s x -d '(implies -n) don\'t use any existing index to generate keyframes'
complete -c aviindex -s v -d 'show version'
complete -c aviindex -l nav_seek -d 'the position you specified via -c.  This also works for multiple -c ranges'
complete -c aviindex -s h -d 'show help text'
complete -c aviindex -o saveidx -d 'FILE and load it again through'
complete -c aviindex -o loadidx -d FILE

