# avimerge
# Autogenerated from man page /usr/lib/jvm/default/man/man1/avimerge.1.gz
complete -c avimerge -s o -d 'Specify the name of the output file'
complete -c avimerge -s i -d 'Specify the name(s) of the input file(s) to merge into the output file'
complete -c avimerge -s p -d 'Specify the name of the audio file to multiplex into the output file'
complete -c avimerge -s b -d 'Specify if avimerge should write an VBR mp3 header into the AVI file'
complete -c avimerge -s c -d 'Drop video frames in case audio is missing [off] '
complete -c avimerge -s f -d 'Read AVI tombstone data for header comments from commentfile'
complete -c avimerge -s x -d 'Read the AVI index from  indexfile'
complete -c avimerge -s a -d 'Specify the number of the audio track you want to use from the  input file'
complete -c avimerge -s A -d 'Specify the number of the audio track you want to use in the output file'

