# avisync
# Autogenerated from man page /usr/lib/jvm/default/man/man1/avisync.1.gz
complete -c avisync -s o -d 'Specify the name of the output file'
complete -c avisync -s i -d 'Specify the name of the input file'
complete -c avisync -s q -d 'be less verbose'
complete -c avisync -s n -d 'shift audio by count frames'
complete -c avisync -s a -d 'Specify the number of the audio channel to shift'
complete -c avisync -s b -d 'Specify if avisync should write an VBR mp3 header into the AVI file'
complete -c avisync -s f -d 'Read AVI tombstone data for header comments from commentfile'

