# avisplit
# Autogenerated from man page /usr/lib/jvm/default/man/man1/avisplit.1.gz
complete -c avisplit -s i -d 'Specify the filename of the file to split into chunks'
complete -c avisplit -s o -d 'Specify the base of the output filename(s) avisplit will then split to base-%…'
complete -c avisplit -s s -d 'Use this option to specify the maximum size (in units of MB) of the chunks av…'
complete -c avisplit -s H -d 'Create only the first num chunks then exit'
complete -c avisplit -s t -d 'Split the input file based on time/framecode (hh:mm:ss. ms)'
complete -c avisplit -s c -d 'Together with -t'
complete -c avisplit -s m -d 'Together with -t.  Force split at upper bondary instead of lower border'
complete -c avisplit -s b -d 'Specify if avisplit should write an VBR mp3 header into the AVI file'
complete -c avisplit -s f -d 'Read AVI tombstone data for header comments from commentfile'
complete -c avisplit -s v -d 'Print only version information and exit.  EXAMPLES The command'

