# bspc
# Autogenerated from man page /usr/lib/jvm/default/man/man1/bspc.1.gz
complete -c bspc -s h -d 'Print the synopsis and exit'
complete -c bspc -s v -d 'Print the version and exit'
complete -c bspc -s c -d 'Use the given configuration file'
complete -c bspc -l presel-dir -d 'under Node in the DOMAINS section below.  [!]local'
complete -c bspc -s f -l focus
complete -c bspc -s a -l activate
complete -c bspc -s d -l to-desktop
complete -c bspc -l follow -d 'is passed, the focused node will stay focused'
complete -c bspc -s m -l to-monitor
complete -c bspc -s n -l to-node
complete -c bspc -s s -l swap
complete -c bspc -s p
complete -c bspc -s o -l presel-ratio
complete -c bspc -l move
complete -c bspc -s z -l resize
complete -c bspc -s r -l ratio
complete -c bspc -s R -l rotate
complete -c bspc -s F -l flip
complete -c bspc -s E -l equalize
complete -c bspc -s B -l balance
complete -c bspc -s C -l circulate
complete -c bspc -s t -l state
complete -c bspc -s g -l flag
complete -c bspc -s l -l layer
complete -c bspc -s i -l insert-receptacle
complete -c bspc -l close
complete -c bspc -s k -l kill
complete -c bspc -l layout
complete -c bspc -l rename
complete -c bspc -s b -l bubble
complete -c bspc -l remove
complete -c bspc -l add-desktops
complete -c bspc -l reorder-desktops
complete -c bspc -l reset-desktops
complete -c bspc -l rectangle
complete -c bspc -s N -l nodes
complete -c bspc -s D -l desktops
complete -c bspc -s M -l monitors
complete -c bspc -s T -l tree
complete -c bspc -l monitor -l desktop -l node
complete -c bspc -l names
complete -c bspc -l dump-state
complete -c bspc -l load-state
complete -c bspc -l add-monitor
complete -c bspc -s O -l reorder-monitors
complete -c bspc -l adopt-orphans
complete -c bspc -l record-history
complete -c bspc -l get-status
complete -c bspc -l restart
complete -c bspc -l add -l one-shot
complete -c bspc -l list
complete -c bspc -l fifo
complete -c bspc -l count

