# bspwm
# Autogenerated from man page /usr/lib/jvm/default/man/man1/bspwm.1.gz
complete -c bspwm -s h -d 'Print the synopsis and exit'
complete -c bspwm -s v -d 'Print the version and exit'
complete -c bspwm -s c -d 'Use the given configuration file'
complete -c bspwm -l presel-dir -d 'under Node in the DOMAINS section below.  [!]local'
complete -c bspwm -s f -l focus
complete -c bspwm -s a -l activate
complete -c bspwm -s d -l to-desktop
complete -c bspwm -l follow -d 'is passed, the focused node will stay focused'
complete -c bspwm -s m -l to-monitor
complete -c bspwm -s n -l to-node
complete -c bspwm -s s -l swap
complete -c bspwm -s p
complete -c bspwm -s o -l presel-ratio
complete -c bspwm -l move
complete -c bspwm -s z -l resize
complete -c bspwm -s r -l ratio
complete -c bspwm -s R -l rotate
complete -c bspwm -s F -l flip
complete -c bspwm -s E -l equalize
complete -c bspwm -s B -l balance
complete -c bspwm -s C -l circulate
complete -c bspwm -s t -l state
complete -c bspwm -s g -l flag
complete -c bspwm -s l -l layer
complete -c bspwm -s i -l insert-receptacle
complete -c bspwm -l close
complete -c bspwm -s k -l kill
complete -c bspwm -l layout
complete -c bspwm -l rename
complete -c bspwm -s b -l bubble
complete -c bspwm -l remove
complete -c bspwm -l add-desktops
complete -c bspwm -l reorder-desktops
complete -c bspwm -l reset-desktops
complete -c bspwm -l rectangle
complete -c bspwm -s N -l nodes
complete -c bspwm -s D -l desktops
complete -c bspwm -s M -l monitors
complete -c bspwm -s T -l tree
complete -c bspwm -l monitor -l desktop -l node
complete -c bspwm -l names
complete -c bspwm -l dump-state
complete -c bspwm -l load-state
complete -c bspwm -l add-monitor
complete -c bspwm -s O -l reorder-monitors
complete -c bspwm -l adopt-orphans
complete -c bspwm -l record-history
complete -c bspwm -l get-status
complete -c bspwm -l restart
complete -c bspwm -l add -l one-shot
complete -c bspwm -l list
complete -c bspwm -l fifo
complete -c bspwm -l count

