# btcflash
# Autogenerated from man page /usr/lib/jvm/default/man/man1/btcflash.1.gz
complete -c btcflash -o help -d 'Prints a short summary of the   p options and exists'
complete -c btcflash -o version -d 'Print version information and exit'
complete -c btcflash -s d -d 'Set the misc debug value to # (with debug=#) or increment the misc debug leve…'
complete -c btcflash -o silent -s s -d 'Do not print out a status report for failed SCSI commands'
complete -c btcflash -s v -d 'Increment the level of general verbosity by one.  This is used e. g'
complete -c btcflash -s V -d 'Increment the verbose level with respect of SCSI command transport by one'
complete -c btcflash -o scanbus -d 'Scan all SCSI devices on all SCSI busses and print the inquiry strings'
complete -c btcflash -o dd -d 'this equals to  debug= 2'
complete -c btcflash -o debug -d 'slows down the process and may be the reason for a buffer underrun'
complete -c btcflash -o VV -d 'will show data buffer content in addition.  Using'

