# cdda2ogg
# Autogenerated from man page /usr/lib/jvm/default/man/man1/cdda2ogg.1.gz
complete -c cdda2ogg -o help -d 'print a short online usage message and exit'
complete -c cdda2ogg -s '*' -d 'Any other option beginning with a \'-\' sign is passed to the cdda2wav program'
complete -c cdda2ogg -s H -s q

