# cdda2wav
# Autogenerated from man page /usr/lib/jvm/default/man/man1/cdda2wav.1.gz
complete -c cdda2wav -o help -d 'display version information for cdda2wav on standard output'
complete -c cdda2wav -o version -d 'display version and Copyright information. SS "Audio options"'
complete -c cdda2wav -o divider -d 'sets rate to 44100Hz /  R divider '
complete -c cdda2wav -o alltracks -d 'copies each track into a separate file'
complete -c cdda2wav -o bits-per-sample -d 'sets   bits per sample per channel:  8 ,  12 or  16 '
complete -c cdda2wav -o channels -d 'use: . RS'
complete -c cdda2wav -o cdrom-endianess -d 'sets endianess of the input samples to \'little\', \'big\', \'machine\' or \'guess\' …'
complete -c cdda2wav -o cuefile -d 'Create a CDRWIN compatible CUE file'
complete -c cdda2wav -o deemphasize -d 'undo the effect of pre-emphasis in the input samples'
complete -c cdda2wav -o cddb -d 'does a cddbp album- and track title lookup based on the cddb id'
complete -c cdda2wav -o duration -d 'sets recording time in seconds or frames (sectors)'
complete -c cdda2wav -o output-endianess -d 'sets endianess of the output samples to \'little\', \'big\' or \'machine\' to  over…'
complete -c cdda2wav -o find-extremes -d 'finds extreme amplitudes in samples'
complete -c cdda2wav -o find-mono -d 'finds if input samples are in mono'
complete -c cdda2wav -o gui -d 'reformats the output for parsing by gui frontends. br . ne 5'
complete -c cdda2wav -o no-infofile -d 'does not write info file, cddb file or cdtext file'
complete -c cdda2wav -o index -d 'selects the start index'
complete -c cdda2wav -o info-only -d 'does not write to a file, it just gives information about the disc'
complete -c cdda2wav -o md5 -d 'enables calculation of MD-5 checksum for all audio bytes from the beginning  …'
complete -c cdda2wav -o mono -d 'sets to mono recording'
complete -c cdda2wav -o no-hidden-track -d 'Ignore hidden tracks on the CD'
complete -c cdda2wav -o no-write -d 'does not write to a file, it just reads (e. g.  for debugging purposes)'
complete -c cdda2wav -o no-textdefaults -d 'By default,  cdda2wav replaces empty CD-Text fields from tracks with the rela…'
complete -c cdda2wav -o no-textfile -d 'If  cdda2wav encounters useful CD-Text information on the CD, it writes a '
complete -c cdda2wav -o offset -d 'starts  offset sectors behind start track (one sector equivalents 1/75 second…'
complete -c cdda2wav -o output-format -d 'can be   wav (for wav files) or  aiff (for apple/sgi aiff files) or  aifc (fo…'
complete -c cdda2wav -o playback-realtime -d 'changes pitch of audio data copied to sound device'
complete -c cdda2wav -o set-overlap -d 'sets the initial number of overlap  sectors for jitter correction in non-para…'
complete -c cdda2wav -o paranoia -d 'use the paranoia library as a filter on top of cdda2wav\'s routines for reading'
complete -c cdda2wav -o paraopts -d 'List is a comma separated list of suboptions passed to the paranoia library'
complete -c cdda2wav -o quiet -d 'quiet operation, no screen output'
complete -c cdda2wav -o rate -d 'sets   rate in samples per second'
complete -c cdda2wav -o dump-rates -d 'shows a list of all sample rates and their dividers'
complete -c cdda2wav -o speed -d 'sets the cdrom device to one of the selectable speeds for reading'
complete -c cdda2wav -o stereo -d 'sets to stereo recording'
complete -c cdda2wav -o start-sector -d 'set an absolute start sector'
complete -c cdda2wav -o trackall -d 'selects the start track and optionally the end track'
complete -c cdda2wav -o verbose-level -d 'Retrieves and prints verbose information about the CD'
complete -c cdda2wav -o wait -d 'waits for signal, then start recording'
complete -c cdda2wav -o max -d 'sets maximum (CD) quality. SS "SCSI options"'
complete -c cdda2wav -o device -d 'uses  device as the source for CDDA reading'
complete -c cdda2wav -o scanbus -d 'Scan all SCSI devices on all SCSI buses and print the inquiry strings'
complete -c cdda2wav -o verbose-scsi -d 'enable SCSI command logging to the console'
complete -c cdda2wav -o silent-scsi -d 'suppress SCSI command error reports to the console'
complete -c cdda2wav -o auxdevice -d 'uses  auxdevice as CDROM drive to allow to send the CDROMMULTISESSION ioctl o…'
complete -c cdda2wav -o interface -d 'specifies the  interface to use for accessing the CDROM: . sp . RS'
complete -c cdda2wav -o interactive -d 'Go into interactive mode that reads commands from  stdin  and writes the text…'
complete -c cdda2wav -o no-fork -d 'Do not fork for extended buffering'
complete -c cdda2wav -o echo -d 'copies audio data to the operating system\'s sound device e. g.   /dev/dsp '
complete -c cdda2wav -o sectors-per-request -d 'reads   sectors per request'
complete -c cdda2wav -o vtoc -d 'and cdda2wav by default writes *. inf files'
complete -c cdda2wav -s h
complete -c cdda2wav -s a
complete -c cdda2wav -s R -d option
complete -c cdda2wav -s B
complete -c cdda2wav -o bulk
complete -c cdda2wav -s b
complete -c cdda2wav -s c
complete -c cdda2wav -s C
complete -c cdda2wav -s t -d 'to switch cdda2wav into a mode that creates a single audio data file for the …'
complete -c cdda2wav -s T
complete -c cdda2wav -s L
complete -c cdda2wav -o '1	disable' -d '0	interactive mode.  The user selects the entry to use.  1	first fit mode'
complete -c cdda2wav -s d
complete -c cdda2wav -s E
complete -c cdda2wav -s F
complete -c cdda2wav -s G
complete -c cdda2wav -s g
complete -c cdda2wav -s H
complete -c cdda2wav -s i
complete -c cdda2wav -s J
complete -c cdda2wav -s M
complete -c cdda2wav -s m
complete -c cdda2wav -s N
complete -c cdda2wav -s e -d 'option, the CD is read and the audio content is played back to the sound devi…'
complete -c cdda2wav -s o
complete -c cdda2wav -s O
complete -c cdda2wav -s p
complete -c cdda2wav -s P
complete -c cdda2wav -s q
complete -c cdda2wav -s r
complete -c cdda2wav -s S
complete -c cdda2wav -s s
complete -c cdda2wav -o track -d and
complete -c cdda2wav -s v
complete -c cdda2wav -s w
complete -c cdda2wav -s x
complete -c cdda2wav -s D
complete -c cdda2wav -s I -d 'option below)'
complete -c cdda2wav -s V
complete -c cdda2wav -s Q
complete -c cdda2wav -s A
complete -c cdda2wav -s n
complete -c cdda2wav -s l
complete -c cdda2wav -o buffers-in-ring -d 'uses a ring buffer with  buffers total'

