# cowthink
# Autogenerated from man page /usr/lib/jvm/default/man/man1/cowthink.1.gz
complete -c cowthink -s n -d 'option.   If it is specified, the given message will not be word-wrapped'
complete -c cowthink -s W -d 'specifies roughly (where the message should be wrapped'
complete -c cowthink -s b -d 'option initiates Borg mode; '
complete -c cowthink -s d -d 'causes the cow to appear dead; '
complete -c cowthink -s g -d 'invokes greedy mode;'
complete -c cowthink -s p -d 'causes a state of paranoia to come over the cow;'
complete -c cowthink -s s -d 'makes the cow appear thoroughly stoned;'
complete -c cowthink -s t -d 'yields a tired cow;'
complete -c cowthink -s w -d 'is somewhat the opposite of '
complete -c cowthink -s y -d 'brings on the cow\'s youthful appearance'
complete -c cowthink -s e -d 'option to select the appearance of the cow\'s eyes, in which case the first tw…'
complete -c cowthink -s T -d 'and tongue_string ; it must be two characters and does not appear by default'
complete -c cowthink -s f -d 'option specifies a particular cow picture file (``cowfile\'\') to use'
complete -c cowthink -s l -d switch

