# cpupower-frequency-info
# Autogenerated from man page /usr/lib/jvm/default/man/man1/cpupower-frequency-info.1.gz
complete -c cpupower-frequency-info -s e -l debug -d 'Prints out debug information'
complete -c cpupower-frequency-info -s f -l freq -d 'Get frequency the CPU currently runs at, according to the cpufreq core'
complete -c cpupower-frequency-info -s w -l hwfreq -d 'Get frequency the CPU currently runs at, by reading it from hardware (only av…'
complete -c cpupower-frequency-info -s l -l hwlimits -d 'Determine the minimum and maximum CPU frequency allowed'
complete -c cpupower-frequency-info -s d -l driver -d 'Determines the used cpufreq kernel driver'
complete -c cpupower-frequency-info -s p -l policy -d 'Gets the currently used cpufreq policy'
complete -c cpupower-frequency-info -s g -l governors -d 'Determines available cpufreq governors'
complete -c cpupower-frequency-info -s a -l related-cpus -d 'Determines which CPUs run at the same hardware frequency'
complete -c cpupower-frequency-info -l affected-cpus -d 'Determines which CPUs need to have their frequency coordinated by software'
complete -c cpupower-frequency-info -s s -l stats -d 'Shows cpufreq statistics if available'
complete -c cpupower-frequency-info -s y -l latency -d 'Determines the maximum latency on CPU frequency changes'
complete -c cpupower-frequency-info -s o -l proc -d 'Prints out information like provided by the /proc/cpufreq interface in 2. 4'
complete -c cpupower-frequency-info -s m -l human -d 'human-readable output for the -f, -w, -s and -y parameters'
complete -c cpupower-frequency-info -s n -l no-rounding -d 'Output frequencies and latencies without rounding off values'

