# cpupower-frequency-set
# Autogenerated from man page /usr/lib/jvm/default/man/man1/cpupower-frequency-set.1.gz
complete -c cpupower-frequency-set -s d -l min -d 'new minimum CPU frequency the governor may select'
complete -c cpupower-frequency-set -s u -l max -d 'new maximum CPU frequency the governor may select'
complete -c cpupower-frequency-set -s g -l governor -d 'new cpufreq governor'
complete -c cpupower-frequency-set -s f -l freq -d 'specific frequency to be set'
complete -c cpupower-frequency-set -s r -l related -d 'modify all hardware-related CPUs at the same time'

