# cpupower-monitor
# Autogenerated from man page /usr/lib/jvm/default/man/man1/cpupower-monitor.1.gz
complete -c cpupower-monitor -s l
complete -c cpupower-monitor -s m
complete -c cpupower-monitor -s i
complete -c cpupower-monitor -s c
complete -c cpupower-monitor -o account -d 'cpuidle timings from sysfs.  command'
complete -c cpupower-monitor -s v

