# cpupower
# Autogenerated from man page /usr/lib/jvm/default/man/man1/cpupower.1.gz
complete -c cpupower -l help -s h
complete -c cpupower -l cpu -s c
complete -c cpupower -l version -s v
complete -c cpupower -l perf-bias -d 'Thomas Renninger <trenn@suse. de>'

