# ctdb_diagnostics
# Autogenerated from man page /usr/lib/jvm/default/man/man1/ctdb_diagnostics.1.gz
complete -c ctdb_diagnostics -s n -d 'Comma separated list of nodes to operate on'
complete -c ctdb_diagnostics -s c -d 'Ignore comment lines (starting with \\*(Aq#\\*(Aq) in file comparisons'
complete -c ctdb_diagnostics -s w -d 'Ignore whitespace in file comparisons'
complete -c ctdb_diagnostics -l no-ads -d 'Do not use commands that assume an Active Directory Server'

