# ctdb
# Autogenerated from man page /usr/lib/jvm/default/man/man1/ctdb.1.gz
complete -c ctdb -s n -d 'The node specified by PNN should be queried for the requested information'
complete -c ctdb -s Y -d 'Produce output in machine readable form for easier parsing by scripts'
complete -c ctdb -s x -d 'Use SEPARATOR to delimit fields in machine readable output.  This implies -Y'
complete -c ctdb -s X -d 'Produce output in machine readable form for easier parsing by scripts'
complete -c ctdb -s t -d 'Indicates that ctdb should wait up to TIMEOUT seconds for a response to most …'
complete -c ctdb -s T -d 'Indicates that TIMELIMIT is the maximum run time (in seconds) for the ctdb co…'
complete -c ctdb -s '?' -l help -d 'Print some help text to the screen'
complete -c ctdb -l usage -d 'Print usage information to the screen'
complete -c ctdb -s d -l debug -d 'Change the debug level for the command.  Default is NOTICE'
complete -c ctdb -l print-emptyrecords
complete -c ctdb -l print-datasize
complete -c ctdb -l print-lmaster
complete -c ctdb -l print-hash
complete -c ctdb -l print-recordflags

