# cue2toc
# Autogenerated from man page /usr/lib/jvm/default/man/man1/cue2toc.1.gz
complete -c cue2toc -s h -d 'print a short help message'
complete -c cue2toc -s n -d 'no CD-Text; disable output of CD-Text information'
complete -c cue2toc -s o -d 'write result to  tocfile instead of standard ouput'
complete -c cue2toc -s q -d 'quiet mode; do not print warnings'
complete -c cue2toc -s v -d 'print version number'
complete -c cue2toc -s w -d 'option to be used for all audio tracks instead of the one in the CUE file'

