# dbwrap_tool
# Autogenerated from man page /usr/lib/jvm/default/man/man1/dbwrap_tool.1.gz
complete -c dbwrap_tool -l persistent -d 'Open the database as a persistent database'
complete -c dbwrap_tool -l non-persistent -d 'Open the database as a non-persistent database'
complete -c dbwrap_tool -s d -l debuglevel -d 'level is an integer from 0 to 10'
complete -c dbwrap_tool -s V -l version -d 'Prints the program version number'
complete -c dbwrap_tool -s s -l configfile -d 'The file specified contains the configuration details required by the server'
complete -c dbwrap_tool -s l -l log-basename -d 'Base directory name for log/debug files.  The extension "'
complete -c dbwrap_tool -l option -d 'Set the smb. conf(5) option "<name>" to value "<value>" from the command line'
complete -c dbwrap_tool -s '?' -l help -d 'Print a summary of command line options'
complete -c dbwrap_tool -l usage -d 'Display brief usage message'

