# discogs
# Autogenerated from man page /usr/lib/jvm/default/man/man1/discogs.1sr.gz
complete -c discogs -o help -d 'Show summary of options (including elvi\\(hyspecific options)'
complete -c discogs -o local-help -d 'Show elvi\\(hyspecific options'
complete -c discogs -o version -d 'Show version of program'
complete -c discogs -o browser -d 'Set browser (default: sensible-browser)'
complete -c discogs -o elvi -d 'Display a list of other Surfraw mechanisms for conquering evil'
complete -c discogs -o escape-url-args -d 'Apply url escaping to arguments (default: yes)'
complete -c discogs -s q -o quote -d 'Bracket arguments with " characters (default: no) Note that putting quotes ro…'

