# dumpexfat
# Autogenerated from man page /usr/lib/jvm/default/man/man8/dumpexfat.8.gz
complete -c dumpexfat -s s -d 'Dump only info from super block'
complete -c dumpexfat -s u -d 'Dump ranges of used sectors starting from 0 and separated with spaces'
complete -c dumpexfat -s f -d 'Print out a list of fragments that compose the given file'
complete -c dumpexfat -s V -d 'Print version and copyright'

