# emacsclient
# Autogenerated from man page /usr/lib/jvm/default/man/man1/emacsclient.1.gz
complete -c emacsclient -s a -l alternate-editor -d 'if the Emacs server is not running, run the specified shell command instead'
complete -c emacsclient -s c -l create-frame -d 'create a new frame instead of trying to use the current Emacs frame'
complete -c emacsclient -s F -l frame-parameters -d 'set the parameters of a newly-created frame'
complete -c emacsclient -s d -l display -d 'tell the server to display the files on the given display'
complete -c emacsclient -s e -l eval -d 'do not visit files but instead evaluate the arguments as Emacs Lisp expressio…'
complete -c emacsclient -s f -l server-file -d 'use TCP configuration file FILENAME for communication'
complete -c emacsclient -s n -l no-wait -d 'returns immediately without waiting for you to "finish" the buffer in Emacs'
complete -c emacsclient -o nw -s t -l tty -d 'open a new Emacs frame on the current terminal'
complete -c emacsclient -s s -l socket-name -d 'use socket named FILENAME for communication'
complete -c emacsclient -s V -l version -d 'print version information and exit'
complete -c emacsclient -s H -l help -d 'print this usage information message and exit EXIT STATUS Normally, the exit …'

