# env_parallel
# Autogenerated from man page /usr/lib/jvm/default/man/man1/env_parallel.1.gz
complete -c env_parallel -l end-session -d 'Undo last --session'
complete -c env_parallel -l record-env -d 'Record all names currently defined to be ignored every time running env_paral…'

