# exfatfsck
# Autogenerated from man page /usr/lib/jvm/default/man/man8/exfatfsck.8.gz
complete -c exfatfsck -s a -d 'Automatically repair the file system.  No user intervention required'
complete -c exfatfsck -s n -d 'No-operation mode: non-interactively check for errors, but don\'t write anythi…'
complete -c exfatfsck -s p -d 'Same as -a for compatibility with other *fsck'
complete -c exfatfsck -s V -d 'Print version and copyright'
complete -c exfatfsck -s y -d 'Same as -a for compatibility with other *fsck'

