# false
# Autogenerated from man page /usr/lib/jvm/default/man/man1/false.1.gz
complete -c false -l help -d 'display this help and exit'
complete -c false -l version -d 'output version information and exit'

