# findsmb
# Autogenerated from man page /usr/lib/jvm/default/man/man1/findsmb.1.gz
complete -c findsmb -s r -d 'Controls whether findsmb takes bugs in Windows95 into account when trying to …'
complete -c findsmb -s B -d 'option.  subnet broadcast address'
complete -c findsmb -l ------------------------------------------------------------------- -d '192. 168. 35. 10   MINESET-TEST1  [DMVENGR] 192. 168. 35'

