# galculator
# Autogenerated from man page /usr/lib/jvm/default/man/man1/galculator.1.gz
complete -c galculator -s h -l help -d 'Show summary of options'
complete -c galculator -s v -l version -d 'Show version of program'

