# gh-issue-delete
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gh-issue-delete.1.gz
complete -c gh-issue-delete -l help -d '	Show help for command'
complete -c gh-issue-delete -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

