# gh-pr
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gh-pr.1.gz
complete -c gh-pr -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format OPTIONS INHERIT…'
complete -c gh-pr -l help -d '	Show help for command EXAMPLE $ gh pr checkout 353 $ gh pr create --fill $ g…'

