# gh-run-rerun
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gh-run-rerun.1.gz
complete -c gh-run-rerun -l help -d '	Show help for command'
complete -c gh-run-rerun -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

