# gh-secret
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gh-secret.1.gz
complete -c gh-secret -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format OPTIONS INHERIT…'
complete -c gh-secret -l help -d '	Show help for command SEE ALSO'

