# gh-workflow
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gh-workflow.1.gz
complete -c gh-workflow -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format OPTIONS INHERIT…'
complete -c gh-workflow -l help -d '	Show help for command SEE ALSO'

