# gperl
# Autogenerated from man page /usr/share/man/man1/gperl.1.gz
complete -c gperl -s h -l help -d 'Print help information with a short explanation of options to standard output'
complete -c gperl -s v -l version -d 'Print version information to standard output'

