# GraphicsMagickWand-config
# Autogenerated from man page /usr/lib/jvm/default/man/man1/GraphicsMagickWand-config.1.gz
complete -c GraphicsMagickWand-config -l cflags -d 'Print the compiler flags that were used to compile  libGraphicsMagick '
complete -c GraphicsMagickWand-config -l cppflags -d 'Print the preprocessor flags that are needed to find the  GraphicsMagick C in…'
complete -c GraphicsMagickWand-config -l exec-prefix -d 'Print the directory under which target specific binaries and executables are …'
complete -c GraphicsMagickWand-config -l ldflags -d 'Print the linker flags that are needed to link with the  GraphicsMagickWand l…'
complete -c GraphicsMagickWand-config -l libs -d 'Print the linker flags that are needed to link a program with  libMagick '
complete -c GraphicsMagickWand-config -l version -d 'Print the version of the GraphicsMagick distribution to standard output'

