# GraphicsMagick-config
# Autogenerated from man page /usr/lib/jvm/default/man/man1/GraphicsMagick-config.1.gz
complete -c GraphicsMagick-config -l cflags -d 'Print the compiler flags that were used to compile   libMagick '
complete -c GraphicsMagick-config -l cppflags -d 'Print the preprocessor flags that are needed to find the  GraphicsMagick C in…'
complete -c GraphicsMagick-config -l exec-prefix -d 'Print the directory under which target specific binaries and executables are …'
complete -c GraphicsMagick-config -l ldflags -d 'Print the linker flags that are needed to link with the  GraphicsMagick libra…'
complete -c GraphicsMagick-config -l libs -d 'Print the linker flags that are needed to link a program with  libGraphicsMag…'
complete -c GraphicsMagick-config -l version -d 'Print the version of the GraphicsMagick distribution to standard output'

