# grl-launch-0
# Autogenerated from man page /usr/lib/jvm/default/man/man1/grl-launch-0.3.1.gz
complete -c grl-launch-0 -s h -l help -d 'Show summary of grl-launch options'
complete -c grl-launch-0 -l help-grl -d 'Show summary of Grilo options'
complete -c grl-launch-0 -l help-all -d 'Show summary of all options'
complete -c grl-launch-0 -s C -l config -d 'Configuration file to send to sources'
complete -c grl-launch-0 -s c -l count -d 'Number of elements to return'
complete -c grl-launch-0 -s d -l delay -d 'Wait some seconds before performing the operation (default 1 second)'
complete -c grl-launch-0 -s f -l flags -d 'List of comma-separated flags to use'
complete -c grl-launch-0 -s F -l full -d 'Full serialize'
complete -c grl-launch-0 -s k -l keys -d 'List of comma-separated keys to retrieve'
complete -c grl-launch-0 -s S -l serialize -d Serialize
complete -c grl-launch-0 -s s -l skip -d 'Number of elements to skip'
complete -c grl-launch-0 -s T -l titles -d 'Print column titles (useful for CSV spreadsheets)'
complete -c grl-launch-0 -s V -l version -d 'Print version EXAMPLES Print the ID for all the items searched in the Tracker…'

