# grub-emu
# Autogenerated from man page /usr/lib/jvm/default/man/man1/grub-emu.1.gz
complete -c grub-emu -s d -l directory -d 'use GRUB files in the directory DIR [default=//boot/grub]'
complete -c grub-emu -s H -l hold -d 'wait until a debugger will attach'
complete -c grub-emu -s m -l device-map -d 'use FILE as the device map [default=//boot/grub/device. map]'
complete -c grub-emu -l memdisk -d 'use FILE as memdisk'
complete -c grub-emu -s r -l root -d 'Set root device'
complete -c grub-emu -s v -l verbose -d 'print verbose messages'
complete -c grub-emu -s '?' -l help -d 'give this help list'
complete -c grub-emu -l usage -d 'give a short usage message'
complete -c grub-emu -s V -l version -d 'print program version'

