# gsl-config
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gsl-config.1.gz
complete -c gsl-config -l version -d 'Print the currently installed version of GSL on the standard output'
complete -c gsl-config -l libs -d 'Print the linker flags that are necessary to link a GSL program, with cblas'
complete -c gsl-config -l libs-without-cblas -d 'Print the linker flags that are necessary to link a GSL program, without cblas'
complete -c gsl-config -l cflags -d 'Print the compiler flags that are necessary to compile a GSL program'
complete -c gsl-config -l prefix -d 'Show the GSL installation prefix'

