# gst-play-1
# Autogenerated from man page /usr/share/man/man1/gst-play-1.0.1.gz
complete -c gst-play-1 -l wait-on-eos -d 'Keep showing the last frame on EOS until quit or playlist change command (gap…'

