# gst-inspect-1
# Autogenerated from man page /usr/share/man/man1/gst-inspect-1.0.1.gz
complete -c gst-inspect-1 -l gst-plugin-path -d 'Add directories separated with \':\' to the plugin search path'

