# gst-launch-1
# Autogenerated from man page /usr/share/man/man1/gst-launch-1.0.1.gz
complete -c gst-launch-1 -l gst-version -d 'Prints the version string of the GStreamer core library'
complete -c gst-launch-1 -l gst-fatal-warnings -d 'Causes GStreamer to abort if a warning message occurs'
complete -c gst-launch-1 -l gst-debug -d 'A comma separated list of category_name:level pairs to specify debugging leve…'
complete -c gst-launch-1 -l gst-debug-level -d 'Sets the threshold for printing debugging messages'
complete -c gst-launch-1 -l gst-debug-no-color -d 'GStreamer normally prints debugging messages so that the messages are color-c…'
complete -c gst-launch-1 -l gst-debug-color-mode -d 'GStreamer normally prints debugging messages so that the messages are color-c…'
complete -c gst-launch-1 -l gst-debug-disable -d 'Disables debugging'
complete -c gst-launch-1 -l gst-debug-help -d 'Prints a list of available debug categories and their default debugging level'
complete -c gst-launch-1 -l gst-plugin-spew -d 'GStreamer info flags to set Enable printout of errors while loading GStreamer…'
complete -c gst-launch-1 -l gst-plugin-path -d 'Add directories separated with \':\' to the plugin search path'
complete -c gst-launch-1 -l gst-plugin-load -d 'Preload plugins specified in a comma-separated list'

