# gst-typefind-1
# Autogenerated from man page /usr/share/man/man1/gst-typefind-1.0.1.gz
complete -c gst-typefind-1 -l gst-plugin-path -d 'Add directories separated with \':\' to the plugin search path'

