# hdifftopam
# Autogenerated from man page /usr/lib/jvm/default/man/man1/hdifftopam.1.gz
complete -c hdifftopam -o pnm -d 'This option tells hdifftopam to create a PNM image (i. e.  PGM or      PPM)'

