# hzip
# Autogenerated from man page /usr/lib/jvm/default/man/man1/hzip.1.gz
complete -c hzip -s h -d 'Display short help description'
complete -c hzip -s P -d 'Encrypted compression by an arbitrary length password'

