# ixquick
# Autogenerated from man page /usr/lib/jvm/default/man/man1/ixquick.1sr.gz
complete -c ixquick -o help -d 'Show summary of options (including elvi\\(hyspecific options)'
complete -c ixquick -o local-help -d 'Show elvi\\(hyspecific options'
complete -c ixquick -o version -d 'Show version of program'
complete -c ixquick -o browser -d 'Set browser (default: sensible-browser)'
complete -c ixquick -o elvi -d 'Display a list of other Surfraw mechanisms for conquering evil'
complete -c ixquick -o escape-url-args -d 'Apply url escaping to arguments (default: yes)'
complete -c ixquick -s q -o quote -d 'Bracket arguments with " characters (default: no) Note that putting quotes ro…'

