# jabswitch-jdk16
# Autogenerated from man page /usr/lib/jvm/default/man/man1/jabswitch-jdk16.1.gz
complete -c jabswitch-jdk16 -o enable
complete -c jabswitch-jdk16 -o disable -d Bridge
complete -c jabswitch-jdk16 -o version -d 'for the jabswitch command'
complete -c jabswitch-jdk16 -s '?' -d 'jabswitch command.  DESCRIPTION'

