# jackd
# Autogenerated from man page /usr/share/man/man1/jackd.1.gz
complete -c jackd -o dguid:0xff2584e39b078a2e -d 'Sometimes resetting the Firewire bus can help ("ffado-test BusReset") if  the…'

