# jarsigner-jdk16
# Autogenerated from man page /usr/lib/jvm/default/man/man1/jarsigner-jdk16.1.gz
complete -c jarsigner-jdk16 -o storetype
complete -c jarsigner-jdk16 -o sigalg
complete -c jarsigner-jdk16 -o 'J-Djava.security.debug' -d 'The jdk. jar. disabledAlgorithms and jdk. security'
complete -c jarsigner-jdk16 -o sigfile -d 'For example, when the option is -sigfile MKSIGN, the files are named MKSIGN'
complete -c jarsigner-jdk16 -o tsa -d '[bu] 2'
complete -c jarsigner-jdk16 -o tsacert -d '[bu] 2'
complete -c jarsigner-jdk16 -o tsapolicyid -d '[bu] 2'
complete -c jarsigner-jdk16 -o tsadigestalg
complete -c jarsigner-jdk16 -o strict -d 'specifying the -verbose and -certs options) to determine if the signature can…'
complete -c jarsigner-jdk16 -o digestalg -o signedjar -d 'TSA-related options are only relevant when signing a JAR file; they aren[aq]t…'
complete -c jarsigner-jdk16 -o keystore -d 'Specifies the URL that tells the keystore location'
complete -c jarsigner-jdk16 -o storepass -d 'Specifies the password that is required to access the keystore'
complete -c jarsigner-jdk16 -o keypass -o certchain -d 'Specifies the password used to protect the private key of the keystore entry …'
complete -c jarsigner-jdk16 -o verify -d 'Verifies a signed JAR file'
complete -c jarsigner-jdk16 -o verbose -d 'When the -verbose option appears on the command line, it indicates that the j…'
complete -c jarsigner-jdk16 -o certs -d 'If the -certs option appears on the command line with the'
complete -c jarsigner-jdk16 -o revCheck -d 'This option enables revocation checking of certificates when signing or verif…'
complete -c jarsigner-jdk16 -o internalsf -d 'In the past, the signature block file generated when a JAR file was signed in…'
complete -c jarsigner-jdk16 -o sectionsonly -d 'If the -sectionsonly option appears on the command line, then the '
complete -c jarsigner-jdk16 -o protected -d 'Values can be either true or false'
complete -c jarsigner-jdk16 -o providerName -d 'If more than one provider was configured in the java'
complete -c jarsigner-jdk16 -o addprovider -o providerArg -d 'Adds a security provider by name (such as SunPKCS11) and an optional configur…'
complete -c jarsigner-jdk16 -o providerClass -d 'Used to specify the name of cryptographic service provider[aq]s master class …'
complete -c jarsigner-jdk16 -o Jjavaoption -d 'Passes through the specified javaoption string directly to the Java interpret…'
complete -c jarsigner-jdk16 -o conf -d 'Specifies a pre-configured options file'
complete -c jarsigner-jdk16 -o altsigner -d 'This option specifies an alternative signing mechanism'
complete -c jarsigner-jdk16 -o altsignerpath -d 'Specifies the path to the class file and any JAR file it depends on'

