# jcmd-jdk16
# Autogenerated from man page /usr/lib/jvm/default/man/man1/jcmd-jdk16.1.gz
complete -c jcmd-jdk16 -o all -d 'Compiler. codecache Prints code cache layout and bounds.  Impact: Low'
complete -c jcmd-jdk16 -s l -d '(BOOLEAN, false) VM'
complete -c jcmd-jdk16 -s i -d '(BOOLEAN, false) [bu] 2'
complete -c jcmd-jdk16 -s s -d subclasses
complete -c jcmd-jdk16 -o verbose -d 'table (BOOLEAN, false) VM. symboltable [options] Dumps the symbol table'
complete -c jcmd-jdk16 -o date -d '(BOOLEAN, false) VM. version Prints JVM version information.  Impact: Low'

