# jdb-jdk16
# Autogenerated from man page /usr/lib/jvm/default/man/man1/jdb-jdk16.1.gz
complete -c jdb-jdk16 -o help -d 'Displays a help message'
complete -c jdb-jdk16 -o sourcepath -d 'Uses the specified path to search for source files in the specified path'
complete -c jdb-jdk16 -o attach -d 'Attaches the debugger to a running JVM with the default connection mechanism'
complete -c jdb-jdk16 -o listen -d 'Waits for a running JVM to connect to the specified address with a standard c…'
complete -c jdb-jdk16 -o listenany -d 'Waits for a running JVM to connect at any available address using a standard …'
complete -c jdb-jdk16 -o launch -d 'Starts the debugged application immediately upon startup of the jdb command'
complete -c jdb-jdk16 -o listconnectors -d 'Lists the connectors available in this JVM'
complete -c jdb-jdk16 -o connect -d 'Connects to the target JVM with the named connector and listed argument values'
complete -c jdb-jdk16 -o dbgtrace -d 'Prints information for debugging the jdb command'
complete -c jdb-jdk16 -o tclient -d 'Runs the application in the Java HotSpot VM client'
complete -c jdb-jdk16 -o tserver -d 'Runs the application in the Java HotSpot VM server'
complete -c jdb-jdk16 -o Joption -d 'Passes option to the JVM, where option is one of the options described on the…'
complete -c jdb-jdk16 -s v -o 'verbose[:class' -d 'Turns on the verbose mode'
complete -c jdb-jdk16 -o Dname -d 'Sets a system property'
complete -c jdb-jdk16 -o classpath -d 'Lists directories separated by colons in which to look for classes'
complete -c jdb-jdk16 -s X -d 'A nonstandard target JVM option'

