# jinfo-jdk16
# Autogenerated from man page /usr/lib/jvm/default/man/man1/jinfo-jdk16.1.gz
complete -c jinfo-jdk16 -o flag -d 'Prints the name and value of the specified command-line flag'
complete -c jinfo-jdk16 -o ']name' -d 'Enables or disables the specified Boolean command-line flag'
complete -c jinfo-jdk16 -o flags -d 'Prints command-line flags passed to the JVM'
complete -c jinfo-jdk16 -o sysprops -d 'Prints Java system properties as name-value pairs'
complete -c jinfo-jdk16 -s h -o help -d 'Prints a help message'

