# jrunscript-jdk16
# Autogenerated from man page /usr/lib/jvm/default/man/man1/jrunscript-jdk16.1.gz
complete -c jrunscript-jdk16 -o cp -o classpath -d 'Indicates where any class files are that the script needs to access'
complete -c jrunscript-jdk16 -o Dname -d 'Sets a Java system property'
complete -c jrunscript-jdk16 -o Jflag -d 'Passes flag directly to the Java Virtual Machine where the jrunscript command…'
complete -c jrunscript-jdk16 -s l -d 'Uses the specified scripting language.  By default, JavaScript is used'
complete -c jrunscript-jdk16 -s e -d 'Evaluates the specified script'
complete -c jrunscript-jdk16 -o encoding -d 'Specifies the character encoding used to read script files'
complete -c jrunscript-jdk16 -s f -d 'Evaluates the specified script file (batch mode)'
complete -c jrunscript-jdk16 -o help -s '?' -d 'Displays a help message and exits'
complete -c jrunscript-jdk16 -s q -d 'Lists all script engines available and exits.  ARGUMENTS'

