# jstatd-jdk16
# Autogenerated from man page /usr/lib/jvm/default/man/man1/jstatd-jdk16.1.gz
complete -c jstatd-jdk16 -o nr -d 'OPTIONS FOR THE JSTATD COMMAND'
complete -c jstatd-jdk16 -s p -d 'This option sets the port number where the RMI registry is expected to be fou…'
complete -c jstatd-jdk16 -s r -d 'This option sets the port number to which the RMI connector is bound'
complete -c jstatd-jdk16 -s n -d 'This option sets the name to which the remote RMI object is bound in the RMI …'
complete -c jstatd-jdk16 -o Joption -d 'This option passes a Java option to the JVM, where the option is one of those…'

