# jstat-jdk16
# Autogenerated from man page /usr/lib/jvm/default/man/man1/jstat-jdk16.1.gz
complete -c jstat-jdk16 -o help -d 'Displays a help message'
complete -c jstat-jdk16 -o options -d 'Displays a list of static options.  See Output Options for the jstat Command'
complete -c jstat-jdk16 -s J -d 'The statOption must come first'
complete -c jstat-jdk16 -o statOption -d 'Determines the statistics information that the jstat command displays'
complete -c jstat-jdk16 -o JjavaOption -d 'Passes javaOption to the Java application launcher'
complete -c jstat-jdk16 -o class -d 'Class loader statistics.  Loaded: Number of classes loaded'
complete -c jstat-jdk16 -o compiler -d 'Java HotSpot VM Just-in-Time compiler statistics'
complete -c jstat-jdk16 -o gc -d 'Garbage collected heap statistics'
complete -c jstat-jdk16 -o gccapacity -d 'Memory pool generation and space capacities'
complete -c jstat-jdk16 -o gccause -d 'This option displays the same summary of garbage collection statistics as the…'
complete -c jstat-jdk16 -o gcnew -d 'New generation statistics.  S0C: Current survivor space 0 capacity (KB)'
complete -c jstat-jdk16 -o gcnewcapacity -d 'New generation space size statistics'
complete -c jstat-jdk16 -o gcold -d 'Old generation size statistics.  MC: Metaspace Committed Size (KB)'
complete -c jstat-jdk16 -o gcoldcapacity -d 'Old generation statistics.  OGCMN: Minimum old generation capacity (KB)'
complete -c jstat-jdk16 -o gcmetacapacity -d 'Metaspace size statistics.  MCMN: Minimum metaspace capacity (KB)'
complete -c jstat-jdk16 -o gcutil -d 'Summary of garbage collection statistics'
complete -c jstat-jdk16 -o printcompilation -d 'Java HotSpot VM compiler method statistics'
complete -c jstat-jdk16 -o XX:+PrintCompilation

