# jstack-jdk16
# Autogenerated from man page /usr/lib/jvm/default/man/man1/jstack-jdk16.1.gz
complete -c jstack-jdk16 -s l -d 'The long listing option prints additional information about locks'
complete -c jstack-jdk16 -s h -o help -d 'Prints a help message'

