# keytool-jdk16
# Autogenerated from man page /usr/lib/jvm/default/man/man1/keytool-jdk16.1.gz
complete -c keytool-jdk16 -s J -d 'command line.  They don[aq]t have any default values'
complete -c keytool-jdk16 -o gencert -d '[bu] 2'
complete -c keytool-jdk16 -o genkeypair -d '[bu] 2'
complete -c keytool-jdk16 -o genseckey -d '[bu] 2'
complete -c keytool-jdk16 -o importcert -d '[bu] 2'
complete -c keytool-jdk16 -o importpass
complete -c keytool-jdk16 -o importkeystore
complete -c keytool-jdk16 -o certreq
complete -c keytool-jdk16 -o exportcert
complete -c keytool-jdk16 -o list -d '[bu] 2'
complete -c keytool-jdk16 -o printcert -d '[bu] 2'
complete -c keytool-jdk16 -o printcertreq -d '[bu] 2'
complete -c keytool-jdk16 -o printcrl
complete -c keytool-jdk16 -o storepasswd -d '[bu] 2'
complete -c keytool-jdk16 -o keypasswd -d '[bu] 2'
complete -c keytool-jdk16 -o delete -d '[bu] 2'
complete -c keytool-jdk16 -o changealias
complete -c keytool-jdk16 -o showinfo -d 'COMMANDS FOR CREATING OR ADDING DATA TO THE KEYSTORE'
complete -c keytool-jdk16 -o keyalg -d '[bu] 2 {-keysize size}: Key bit size [bu] 2 {-groupname name}: Group name'
complete -c keytool-jdk16 -o startdate -d 'should be considered valid'
complete -c keytool-jdk16 -o keystore -d 'The -keypass value must contain at least six characters'
complete -c keytool-jdk16 -o alias -d 'If -file file is not specified, then the certificate or certificate chain is …'
complete -c keytool-jdk16 -o srckeystore -d '[bu] 2 {-destkeystore keystore}: Destination keystore name [bu] 2 {-srcstoret…'
complete -c keytool-jdk16 -o destkeystore -d 'keystore Use the -importkeystore command to import a single entry or all entr…'
complete -c keytool-jdk16 -o srckeypass -d 'If -srckeypass isn[aq]t provided, then the keytool command attempts to use -s…'
complete -c keytool-jdk16 -o destkeypass -o deststorepass
complete -c keytool-jdk16 -o srcstorepass -d 'If -srcstorepass is not provided or is incorrect, then the user is prompted f…'
complete -c keytool-jdk16 -o sslserver -d 'signed JAR file specified by -jarfile JAR_file'
complete -c keytool-jdk16 -o 'J-Dhttps.proxyHost'
complete -c keytool-jdk16 -o 'J-Dhttps.proxyPort' -d 'command line for proxy tunneling'
complete -c keytool-jdk16 -o keypass -o new -d 'new_keypass.  The password value must contain at least six characters'
complete -c keytool-jdk16 -l help -d 'When the -v option appears, it signifies verbose mode, which means that more …'
complete -c keytool-jdk16 -o storetype -d 'This qualifier specifies the type of keystore to be instantiated'
complete -c keytool-jdk16 -o cacerts -d 'Operates on the cacerts keystore '
complete -c keytool-jdk16 -o storepass -d 'The password that is used to protect the integrity of the keystore'
complete -c keytool-jdk16 -o providername -d 'Used to identify a cryptographic service provider[aq]s name when listed in th…'
complete -c keytool-jdk16 -o addprovider -d 'Used to add a security provider by name (such as SunPKCS11) '
complete -c keytool-jdk16 -o providerclass -d 'Used to specify the name of a cryptographic service provider[aq]s master clas…'
complete -c keytool-jdk16 -o providerpath -d 'Used to specify the provider classpath'
complete -c keytool-jdk16 -o providerarg -d 'Used with the -addprovider or -providerclass option to represent an optional …'
complete -c keytool-jdk16 -o protected -d 'Specify this value as true when a password must be specified by way of a prot…'
complete -c keytool-jdk16 -o srcprotected -o destprotected -d 'the source keystore and the destination keystore respectively'
complete -c keytool-jdk16 -o ext -d 'Denotes an X. 509 certificate extension'
complete -c keytool-jdk16 -o conf -d 'Specifies a pre-configured options file.  PRE-CONFIGURED OPTIONS FILE'
complete -c keytool-jdk16 -o keysize -d '    2048 (when using -genkeypair and -keyalg is "RSA", "DSA", or "RSASSA-PSS"…'
complete -c keytool-jdk16 -o validity
complete -c keytool-jdk16 -o file -d '    stdin (if reading)     stdout (if writing)'
complete -c keytool-jdk16 -o noprompt -d 'Make sure that the displayed certificate fingerprints match the expected fing…'
complete -c keytool-jdk16 -o srcalias -o destalias -d 'password -destkeypass password'
complete -c keytool-jdk16 -l ---BEGIN
complete -c keytool-jdk16 -l ---END -d 'X. 500 Distinguished Names X'
complete -c keytool-jdk16 -o dname -d 'the string must be in the following format: CN=cName, OU=orgUnit, O=org, L=ci…'
complete -c keytool-jdk16 -o trustcacerts

