# kinit-jdk16
# Autogenerated from man page /usr/lib/jvm/default/man/man1/kinit-jdk16.1.gz
complete -c kinit-jdk16 -s A -d 'Doesn[aq]t include addresses'
complete -c kinit-jdk16 -s f -d 'Issues a forwardable ticket'
complete -c kinit-jdk16 -s p -d 'Issues a proxiable ticket'
complete -c kinit-jdk16 -s c -d 'The cache name (for example, FILE:D:\\temp\\mykrb5cc)'
complete -c kinit-jdk16 -s l -d 'Sets the lifetime of a ticket'
complete -c kinit-jdk16 -s r -d 'Sets the total lifetime that a ticket can be renewed'
complete -c kinit-jdk16 -s R -d 'Renews a ticket'
complete -c kinit-jdk16 -s k -d 'Uses keytab'
complete -c kinit-jdk16 -s t -d 'The keytab name (for example, D:\\winnt\\profiles\\duke\\krb5. keytab)'

