# kjs5
# Autogenerated from man page /usr/lib/jvm/default/man/man1/kjs5.1.gz
complete -c kjs5 -l help -o help -s h -d 'Show kjs5 usage'
complete -c kjs5 -l version -o version -s v -d 'Show kjs5 version'
complete -c kjs5 -s e -d 'Executes the statement and exits'

