# klist-jdk16
# Autogenerated from man page /usr/lib/jvm/default/man/man1/klist-jdk16.1.gz
complete -c klist-jdk16 -s c -d 'Specifies that the credential cache is to be listed'
complete -c klist-jdk16 -s f -d 'Show credential flags'
complete -c klist-jdk16 -s e -d 'Show the encryption type'
complete -c klist-jdk16 -s a -d 'Show addresses'
complete -c klist-jdk16 -s n -d 'If the -a option is specified, don[aq]t reverse resolve addresses'
complete -c klist-jdk16 -s k -d 'Specifies that key tab is to be listed.  List the keytab entries'
complete -c klist-jdk16 -s t -d 'Show keytab entry timestamps'
complete -c klist-jdk16 -s K -d 'Show keytab entry DES keys'
complete -c klist-jdk16 -o help -d 'Displays instructions.  EXAMPLES'

