# ktab-jdk16
# Autogenerated from man page /usr/lib/jvm/default/man/man1/ktab-jdk16.1.gz
complete -c ktab-jdk16 -s l -d 'Lists the keytab name and entries'
complete -c ktab-jdk16 -s a -s n -d 'Adds new key entries to the keytab for the given principal name with an optio…'
complete -c ktab-jdk16 -s d -s e -d 'Deletes key entries from the keytab for the specified principal'
complete -c ktab-jdk16 -o help -d 'Displays instructions.  COMMON OPTIONS'
complete -c ktab-jdk16 -s k -d 'Specifies the keytab name and path with the FILE: prefix'

