# lemonbar
# Autogenerated from man page /usr/lib/jvm/default/man/man1/lemonbar.1
complete -c lemonbar -s h -d 'Display the help and exit'
complete -c lemonbar -s g -d 'Set the window geometry'
complete -c lemonbar -s o -d 'Set next output to name.  May be used multiple times; order is significant'
complete -c lemonbar -s b -d 'Dock the bar at the bottom of the screen'
complete -c lemonbar -s d -d 'Force docking without asking the window manager'
complete -c lemonbar -s f -d 'Specifies a font to use'
complete -c lemonbar -s p -d 'Make the bar permanent, don\'t exit after the standard input is closed'
complete -c lemonbar -s n -d 'Set the \\s-1WM_NAME\\s0 atom value for the bar'
complete -c lemonbar -s u -d 'Sets the underline width in pixels.  The default is 1'
complete -c lemonbar -s B -d 'Set the background color of the bar'
complete -c lemonbar -s F -d 'Set the foreground color of the bar.  Accepts the same color formats as -B'

