# libwacom-list-local-devices
# Autogenerated from man page /usr/lib/jvm/default/man/man1/libwacom-list-local-devices.1.gz
complete -c libwacom-list-local-devices -l format -d 'Sets the output format to be used'
complete -c libwacom-list-local-devices -l database -d 'Sets the data directory path to be used'

