# ltdbtool
# Autogenerated from man page /usr/lib/jvm/default/man/man1/ltdbtool.1.gz
complete -c ltdbtool -s e -d 'Dump empty records.  These are normally excluded'
complete -c ltdbtool -s p -d 'Dump with header information, similar to "ctdb catdb"'
complete -c ltdbtool -s o -d 'Specify how to determine the CTDB record header size for the output database,…'
complete -c ltdbtool -s S -d 'Explicitly specify the CTDB record header SIZE of the input database in bytes'
complete -c ltdbtool -s O -d 'Explicitly specify the CTDB record header SIZE for the output database in byt…'
complete -c ltdbtool -s h -d 'Print help text'
complete -c ltdbtool -s s

