# macptopbm
# Autogenerated from man page /usr/lib/jvm/default/man/man1/macptopbm.1.gz
complete -c macptopbm -o extraskip -d 'This option is to get around a problem with some methods of transferring file…'

