# mdfind
# Autogenerated from man page /usr/lib/jvm/default/man/man1/mdfind.1.gz
complete -c mdfind -s p -l path -d 'Server side path to search, defaults to "/"'
complete -c mdfind -s L -l live -d 'Query remains running'

