# mkexfatfs
# Autogenerated from man page /usr/lib/jvm/default/man/man8/mkexfatfs.8.gz
complete -c mkexfatfs -s i -d 'A 32-bit hexadecimal number.  By default a value based on current time is set'
complete -c mkexfatfs -s n -d 'Volume name (label), up to 15 characters.  By default no label is set'
complete -c mkexfatfs -s p -d 'First sector of the partition starting from the beginning of the whole disk'
complete -c mkexfatfs -s s -d 'Number of physical sectors per cluster (cluster is an allocation unit in exFA…'
complete -c mkexfatfs -s V -d 'Print version and copyright'

