# mpd
# Autogenerated from man page /usr/lib/jvm/default/man/man1/mpd.1.gz
complete -c mpd -l help -d 'Output a brief help message'
complete -c mpd -l kill -d 'Kill the currently running mpd session'
complete -c mpd -l no-config -d 'Don\\(aqt read from the configuration file'
complete -c mpd -l no-daemon -d 'Don\\(aqt detach from console'
complete -c mpd -l stderr -d 'Print messages to stderr'
complete -c mpd -l verbose -d 'Verbose logging'
complete -c mpd -l version -d 'Print version information'

