# mtrace
# Autogenerated from man page /usr/lib/jvm/default/man/man1/mtrace.1.gz
complete -c mtrace -l help -d 'Print help and exit'
complete -c mtrace -l version -d 'Print version information and exit'

