# ndctl-remove-passphrase
# Autogenerated from man page /usr/lib/jvm/default/man/man1/ndctl-remove-passphrase.1.gz
complete -c ndctl-remove-passphrase -s b -l bus
complete -c ndctl-remove-passphrase -s v -l verbose

