# numastat
# Autogenerated from man page /usr/share/man/man8/numastat.8.gz
complete -c numastat -o s2 -d 'the last option character in a compound option character string'
complete -c numastat -s z -d 'Skip display of table rows and columns of only zero valuess'

