# nuspell
# Autogenerated from man page /usr/lib/jvm/default/man/man1/nuspell.1.gz
complete -c nuspell -s d -d 'use \\f[I]di_CT\\f[R] dictionary.  Only one dictionary is currently supported'
complete -c nuspell -s D -d 'print search paths and available dictionaries and exit'
complete -c nuspell -s i -d 'input/output encoding, default is active locale'
complete -c nuspell -s l -d 'print only misspelled words or lines'
complete -c nuspell -s G -d 'print only correct words or lines'
complete -c nuspell -s L -d 'lines mode'
complete -c nuspell -s s -d 'use simple white-space text segmentation to extract words instead of the defa…'
complete -c nuspell -s h -l help -d 'display this help and exit'
complete -c nuspell -s v -l version -d 'print version number and exit ENVIRONMENT'

