# onnode
# Autogenerated from man page /usr/lib/jvm/default/man/man1/onnode.1.gz
complete -c onnode -s c -d 'Execute COMMAND in the current working directory on the specified nodes'
complete -c onnode -s f -d 'Specify an alternative nodes FILENAME to use instead of the default'
complete -c onnode -s i -d 'Keep standard input open, allowing data to be piped to onnode'
complete -c onnode -s n -d 'Allow nodes to be specified by name rather than node numbers'
complete -c onnode -s p -d 'Run COMMAND in parallel on the specified nodes'
complete -c onnode -s P -d 'Push files to nodes'
complete -c onnode -s q -d 'Do not print node addresses'
complete -c onnode -s v -d 'Print node addresses even if only one node is specified'
complete -c onnode -s h -l help -d 'Show a short usage guide'

