# opensearch-genquery
# Autogenerated from man page /usr/lib/jvm/default/man/man1/opensearch-genquery.1.gz
complete -c opensearch-genquery -s q -d 'Give no output on errors'
complete -c opensearch-genquery -s H -d 'Request \\s-1HTML\\s0 response'
complete -c opensearch-genquery -s A -d 'Request Atom response'
complete -c opensearch-genquery -s R -d 'Request \\s-1RSS\\s0 response'
complete -c opensearch-genquery -s c -l count -d 'Request \\s-1COUNT\\s0 results. Sp OpenSearch parameter: count'
complete -c opensearch-genquery -s i -l startindex -d 'Request results start at offset \\s-1NUM. \\s0 '
complete -c opensearch-genquery -s p -l startpage -d 'Request results page \\s-1PAGENUM. \\s0 . Sp OpenSearch parameter: pageIndex'
complete -c opensearch-genquery -s l -l language -d 'Request results in \\s-1LANG'
complete -c opensearch-genquery -s O -l outputencoding -d 'Request results encoded in \\s-1ENC\\s0 (default: \\s-1UTF-8\\s0)'
complete -c opensearch-genquery -s I -l inputencoding -d 'Specify search terms are encoded in \\s-1ENC\\s0 (default: \\s-1UTF-8\\s0)'
complete -c opensearch-genquery -s h -l help -d 'Show a short help message'

