# opensearch-discover
# Autogenerated from man page /usr/lib/jvm/default/man/man1/opensearch-discover.1.gz
complete -c opensearch-discover -s q -l quiet -d 'Give no output on errors'
complete -c opensearch-discover -s v -l verbose -d 'Verbose: display titles with links'
complete -c opensearch-discover -o 't\\s-1TITLE\\s0' -l title -d 'Only display links matching \\s-1TITLE\\s0, a case-insensitive perl regular exp…'
complete -c opensearch-discover -s 1 -l first -d 'Only display first (matching) link.  This is the default'
complete -c opensearch-discover -s a -l all -d 'Display all (matching) links'

