# ping_pong
# Autogenerated from man page /usr/lib/jvm/default/man/man1/ping_pong.1.gz
complete -c ping_pong -s r -d 'test read performance'
complete -c ping_pong -s w -d 'test write performance'
complete -c ping_pong -s m -d 'use mmap'
complete -c ping_pong -s c -d 'validate the locks'

