# plaympeg
# Autogenerated from man page /usr/lib/jvm/default/man/man1/plaympeg.1.gz
complete -c plaympeg -l help -d 'Show short usage information'
complete -c plaympeg -l noaudio -d 'Don\'t play the audio stream (if available)'
complete -c plaympeg -l novideo -d 'Don\'t play the video stream (if available)'
complete -c plaympeg -l fullscreen -d 'Play the MPEG video stream in fullscreen mode (this requires root privileges …'
complete -c plaympeg -s 2 -l double -d 'Play the MPEG video stream at double size'
complete -c plaympeg -s l -l loop -d 'Play the stream (audio or video) over and over again'
complete -c plaympeg -s v -l volume -d 'Set the volume of the audio stream to N% (N in the range of 0 to 100)'
complete -c plaympeg -s s -l scale -d 'Play the MPEG video stream at S size SEE ALSO SMPEG home page at http://www'

