# pldd
# Autogenerated from man page /usr/lib/jvm/default/man/man1/pldd.1.gz
complete -c pldd -s '?' -l help -d 'Display a help message and exit'
complete -c pldd -l usage -d 'Display a short usage message and exit'
complete -c pldd -s V -l version -d 'Display program version information and exit'

