# rasttopnm
# Autogenerated from man page /usr/lib/jvm/default/man/man1/rasttopnm.1.gz
complete -c rasttopnm -o index -d 'This odd option tells rasttopnm to use the color map indices in the raster as…'

