# regedit
# Autogenerated from man page /usr/share/man/man1/regedit.1.gz
complete -c regedit -s E -d 'Exports the content of the specified registry key to the specified file'
complete -c regedit -s D -d 'Deletes the specified registry key'
complete -c regedit -s L -d 'Specifies the location of the system. dat registry file (ignored)'
complete -c regedit -s R -d 'Specifies the location of the user. dat registry file (ignored)'
complete -c regedit -s C -d 'Create registry from file. reg (unimplemented)'

