# rmid-jdk16
# Autogenerated from man page /usr/lib/jvm/default/man/man1/rmid-jdk16.1.gz
complete -c rmid-jdk16 -o 'J-Dsun.rmi.activation.execPolicy'
complete -c rmid-jdk16 -o port -d 'For example, the following command starts the activation system daemon and a …'
complete -c rmid-jdk16 -o Coption -d 'Specifies an option that[aq]s passed as a command-line argument to each child…'
complete -c rmid-jdk16 -o Joption -d 'Specifies an option that[aq]s passed to the Java interpreter running RMID com…'
complete -c rmid-jdk16 -o Dproperty -d 'The com. sun. rmi. rmid'
complete -c rmid-jdk16 -o log -d 'Specifies the name of the directory that the activation system daemon uses to…'
complete -c rmid-jdk16 -o stop -d 'Stops the current invocation of the rmid command for a port specified by the …'

