# rmiregistry-jdk16
# Autogenerated from man page /usr/lib/jvm/default/man/man1/rmiregistry-jdk16.1.gz
complete -c rmiregistry-jdk16 -o Joption -d 'Used with any Java option to pass the option following the'
complete -c rmiregistry-jdk16 -s J -s J -d 'Java interpreter'

