# rmiregistry-openjdk16
# Autogenerated from man page /usr/lib/jvm/default/man/man1/rmiregistry-openjdk16.1.gz
complete -c rmiregistry-openjdk16 -o Joption -d 'Used with any Java option to pass the option following the'
complete -c rmiregistry-openjdk16 -s J -s J -d 'Java interpreter'

