# rsync
# Autogenerated from man page /usr/share/man/man1/rsync.1.gz
complete -c rsync -o rlptgoD
complete -c rsync -l no-D
complete -c rsync -l stop-after
complete -c rsync -l stop-at
complete -c rsync -l checksum-seed
complete -c rsync -l daemon
complete -c rsync -l config
complete -c rsync -l dparam
complete -c rsync -l no-detach
complete -c rsync -o @0 -d 'between ext3 and ext4, or if the receiving rsync is older than 3. 1. 3'
complete -c rsync -l no-blocking-io -l no-dirs -d 'long option name after the "no-" prefix (e. g.  --no-R is the same as'
complete -c rsync -l no-relative -d 'For example: if you want to use -a (--archive) but don\'t want -o (--owner), i…'
complete -c rsync -l no-o -l no-owner -d 'The order of the options is important: if you specify --no-r -a, the'
complete -c rsync -l no-r -d 'Note also that the side-effects of the --files-from option are NOT positional…'
complete -c rsync -l old-d -d 'an older rsync to list a single directory without recursing'
complete -c rsync -l no-inc-recursive
complete -c rsync -l delete-WHEN
complete -c rsync -o w1 -d '(Note that ssh users can alternately customize site-specific connect options …'
complete -c rsync -l no-R -d 'o The --dirs (-d) option is implied, which will create directories specified …'
complete -c rsync -l no-compress -d 'The compression options that you may be able to use are:'
complete -c rsync -l new-compress -d 'or --compress-choice=zlibx option in a backward-compatible manner that more r…'
complete -c rsync -l no-h -d '11 characters'
complete -c rsync -o vv -d 'file is included or excluded'

