# samba-tool
# Autogenerated from man page /usr/lib/jvm/default/man/man8/samba-tool.8.gz
complete -c samba-tool -s h -l help -d 'Show this help message and exit'
complete -c samba-tool -l realm -d 'Set the realm name'
complete -c samba-tool -l simple-bind-dn -d 'DN to use for a simple bind'
complete -c samba-tool -l password -d Password
complete -c samba-tool -s U -l username -d Username
complete -c samba-tool -s W -l workgroup -d Workgroup
complete -c samba-tool -s N -l no-pass -d 'Don\\*(Aqt ask for a password'
complete -c samba-tool -s k -l kerberos -d 'Use Kerberos'
complete -c samba-tool -l ipaddress -d 'IP address of the server'
complete -c samba-tool -s d -l debuglevel -d 'level is an integer from 0 to 10'
complete -c samba-tool -s V -l version -d 'Prints the program version number'
complete -c samba-tool -s s -l configfile -d 'The file specified contains the configuration details required by the server'
complete -c samba-tool -s l -l log-basename -d 'Base directory name for log/debug files.  The extension "'
complete -c samba-tool -l option -d 'Set the smb. conf(5) option "<name>" to value "<value>" from the command line'
complete -c samba-tool -l computerou
complete -c samba-tool -l description
complete -c samba-tool -l ip-address
complete -c samba-tool -l service-principal-name
complete -c samba-tool -l prepare-oldjoin
complete -c samba-tool -l editor
complete -c samba-tool -l attributes
complete -c samba-tool -l ou
complete -c samba-tool -l surname
complete -c samba-tool -l given-name
complete -c samba-tool -l initials
complete -c samba-tool -l display-name
complete -c samba-tool -l job-title
complete -c samba-tool -l department
complete -c samba-tool -l company
complete -c samba-tool -l mail-address
complete -c samba-tool -l internet-address
complete -c samba-tool -l telephone-number
complete -c samba-tool -l mobile-number
complete -c samba-tool -l physical-delivery-office
complete -c samba-tool -l full-dn
complete -c samba-tool -l force-new-cn
complete -c samba-tool -l reset-cn
complete -c samba-tool -l hide-expired
complete -c samba-tool -l hide-disabled
complete -c samba-tool -l samaccountname
complete -c samba-tool -l use-ntvfs
complete -c samba-tool -l service
complete -c samba-tool -l use-s3fs
complete -c samba-tool -l xattr-backend
complete -c samba-tool -l eadb-file
complete -c samba-tool -l recursive
complete -c samba-tool -l follow-symlinks
complete -c samba-tool -l verbose
complete -c samba-tool -l force-subtree-delete
complete -c samba-tool -s r
complete -c samba-tool -s b -l base-dn
complete -c samba-tool -l upn
complete -c samba-tool -l distance
complete -c samba-tool -l dot
complete -c samba-tool -l xdot

