# scgcheck
# Autogenerated from man page /usr/lib/jvm/default/man/man1/scgcheck.1.gz
complete -c scgcheck -o version -d 'Print version information and exit'
complete -c scgcheck -o auto -d 'Instead of asking to confirm each test before runing it,   scgcheck tries to …'
complete -c scgcheck -s d -d 'Set the misc debug value to # (with debug=#) or increment the misc debug leve…'
complete -c scgcheck -o silent -s s -d 'Do not print out a status report for failed SCSI commands'
complete -c scgcheck -s v -d 'Increment the level of general verbosity by one.  This is used e. g'
complete -c scgcheck -s V -d 'Increment the verbose level with respect of SCSI command transport by one'
complete -c scgcheck -o scanbus -d 'option of  scgcheck described below'
complete -c scgcheck -o dd -d 'this equals to  debug= 2'
complete -c scgcheck -o debug -d 'slows down the process and may be the reason for a buffer underrun'
complete -c scgcheck -o VV -d 'will show data buffer content in addition.  Using'

