# scgskeleton
# Autogenerated from man page /usr/lib/jvm/default/man/man1/scgskeleton.1.gz
complete -c scgskeleton -o help -d 'Prints a short summary of the   p options and exists'
complete -c scgskeleton -o version -d 'Print version information and exit'
complete -c scgskeleton -s d -d 'Set the misc debug value to # (with debug=#) or increment the misc debug leve…'
complete -c scgskeleton -o silent -s s -d 'Do not print out a status report for failed SCSI commands'
complete -c scgskeleton -s v -d 'Increment the level of general verbosity by one.  This is used e. g'
complete -c scgskeleton -s V -d 'Increment the verbose level with respect of SCSI command transport by one'
complete -c scgskeleton -o scanbus -d 'option of  scgskeleton described below'
complete -c scgskeleton -o dd -d 'this equals to  debug= 2'
complete -c scgskeleton -o debug -d 'slows down the process and may be the reason for a buffer underrun'
complete -c scgskeleton -o VV -d 'will show data buffer content in addition.  Using'

