# serialver-jdk16
# Autogenerated from man page /usr/lib/jvm/default/man/man1/serialver-jdk16.1.gz
complete -c serialver-jdk16 -o classpath -d 'Sets the search path for application classes and resources'
complete -c serialver-jdk16 -o Joption -d 'Passes the specified option to the Java Virtual Machine, where option is one …'
complete -c serialver-jdk16 -o 'J-Djava.security.manager' -d 'When necessary, a security policy can be specified with the following option:'
complete -c serialver-jdk16 -o 'J-Djava.security.policy'

