# sfconvert
# Autogenerated from man page /usr/lib/jvm/default/man/man1/sfconvert.1.gz
complete -c sfconvert -l help -s h -d 'Print help message'
complete -c sfconvert -l version -s v -d 'Print version information'

