# smbcontrol
# Autogenerated from man page /usr/lib/jvm/default/man/man1/smbcontrol.1.gz
complete -c smbcontrol -s '?' -l help -d 'Print a summary of command line options'
complete -c smbcontrol -l usage -d 'Display brief usage message'
complete -c smbcontrol -s d -l debuglevel -d 'level is an integer from 0 to 10'
complete -c smbcontrol -s V -l version -d 'Prints the program version number'
complete -c smbcontrol -s s -l configfile -d 'The file specified contains the configuration details required by the server'
complete -c smbcontrol -s l -l log-basename -d 'Base directory name for log/debug files.  The extension "'
complete -c smbcontrol -l option -d 'Set the smb. conf(5) option "<name>" to value "<value>" from the command line'
complete -c smbcontrol -s t -l timeout -d 'Set timeout to seconds'

