# speedtest-cli
# Autogenerated from man page /usr/lib/jvm/default/man/man1/speedtest-cli.1.gz
complete -c speedtest-cli -s h -l help
complete -c speedtest-cli -l no-download
complete -c speedtest-cli -l no-upload
complete -c speedtest-cli -l single
complete -c speedtest-cli -l bytes
complete -c speedtest-cli -l share
complete -c speedtest-cli -l simple
complete -c speedtest-cli -l csv
complete -c speedtest-cli -l csv-delimiter
complete -c speedtest-cli -l csv-header
complete -c speedtest-cli -l json
complete -c speedtest-cli -l list
complete -c speedtest-cli -l server
complete -c speedtest-cli -l exclude
complete -c speedtest-cli -l mini
complete -c speedtest-cli -l source
complete -c speedtest-cli -l timeout
complete -c speedtest-cli -l secure
complete -c speedtest-cli -l no-pre-allocate
complete -c speedtest-cli -l version

