# sr
# Autogenerated from man page /usr/lib/jvm/default/man/man1/sr.1.gz
complete -c sr -o help -d 'Show summary of options (including elvi\\(hyspecific options)'
complete -c sr -o local-help -d 'Show elvi\\(hyspecific options'
complete -c sr -o version -d 'Show version of program'
complete -c sr -o browser -d 'Set browser (default: sensible-browser)'
complete -c sr -o elvi -d 'Display a list of other Surfraw mechanisms for conquering evil'
complete -c sr -o escape-url-args -d 'Apply url escaping to arguments (default: yes)'
complete -c sr -s q -o quote -d 'Bracket all arguments with " characters (default: no)'

