# stack
# Autogenerated from man page /usr/lib/jvm/default/man/man1/stack.1sr.gz
complete -c stack -o help -d 'Show summary of options (including elvi\\(hyspecific options)'
complete -c stack -o local-help -d 'Show elvi\\(hyspecific options'
complete -c stack -o version -d 'Show version of program'
complete -c stack -o browser -d 'Set browser (default: sensible-browser)'
complete -c stack -o elvi -d 'Display a list of other Surfraw mechanisms for conquering evil'
complete -c stack -o escape-url-args -d 'Apply url escaping to arguments (default: yes)'
complete -c stack -s q -o quote -d 'Bracket arguments with " characters (default: no) Note that putting quotes ro…'

