# surfraw-update-path
# Autogenerated from man page /usr/lib/jvm/default/man/man1/surfraw-update-path.1.gz
complete -c surfraw-update-path -o check -d 'Checks to see if the surfraw config code is present.  This is the default'
complete -c surfraw-update-path -o add -d 'Adds the surfraw config code'
complete -c surfraw-update-path -o remove -d 'Removes the surfraw config code'
complete -c surfraw-update-path -o sys -d 'Updates the system-wide shell config instead of the user'
complete -c surfraw-update-path -o shell -d 'Selects the shell to configure'
complete -c surfraw-update-path -o all -d 'Attempts to configure the startup files for all known shells'

