# surfraw
# Autogenerated from man page /usr/lib/jvm/default/man/man1/surfraw.1.gz
complete -c surfraw -o help -d 'Show summary of options (including elvi\\(hyspecific options)'
complete -c surfraw -o local-help -d 'Show elvi\\(hyspecific options'
complete -c surfraw -o version -d 'Show version of program'
complete -c surfraw -o browser -d 'Set browser (default: sensible-browser)'
complete -c surfraw -o elvi -d 'Display a list of other Surfraw mechanisms for conquering evil'
complete -c surfraw -o escape-url-args -d 'Apply url escaping to arguments (default: yes)'
complete -c surfraw -s q -o quote -d 'Bracket all arguments with " characters (default: no)'

