# sxhkd
# Autogenerated from man page /usr/lib/jvm/default/man/man1/sxhkd.1.gz
complete -c sxhkd -s h -d 'Print the synopsis to standard output and exit'
complete -c sxhkd -s v -d 'Print the version information to standard output and exit'
complete -c sxhkd -s m -d 'Handle the first COUNT mapping notify events'
complete -c sxhkd -s t -d 'Timeout in seconds for the recording of chord chains'
complete -c sxhkd -s c -d 'Read the main configuration from the given file'
complete -c sxhkd -s r -d 'Redirect the commands output to the given file'
complete -c sxhkd -s s -d 'Output status information to the given FIFO'
complete -c sxhkd -s a -d 'Name of the keysym used for aborting chord chains'

