# tccat
# Autogenerated from man page /usr/lib/jvm/default/man/man1/tccat.1.gz
complete -c tccat -s i -d 'Specify input source.   If ommited, stdin is assumed'
complete -c tccat -s t -d 'Tell tccat about the type of input'
complete -c tccat -s T -d 'Select DVD  title and extract only a single  chapter with selected viewing  a…'
complete -c tccat -s L -d 'This option tells tccat to loop through all chapters starting at the one give…'
complete -c tccat -s S -d 'Seek to program stream (VOB) offset nx2kB before starting output'
complete -c tccat -s P -d 'Stream full DVD title specified by -T'
complete -c tccat -s a -d 'Use this option to dump an AVI-file/socket audio stream'
complete -c tccat -s d -d 'With this option you can specify a bitmask to enable different levels of verb…'
complete -c tccat -s v -d 'Print version information and exit'

