# tcdecode
# Autogenerated from man page /usr/lib/jvm/default/man/man1/tcdecode.1.gz
complete -c tcdecode -s i -d 'Specify input source.   If ommited, stdin is assumed'
complete -c tcdecode -s g -d 'video frame width and height [720x576]'
complete -c tcdecode -s C -d 'decode and print out only this frame interval (video) or bytes (audio) [all]'
complete -c tcdecode -s x -d 'source codec, if not detected of reading from stdin'
complete -c tcdecode -s t -d 'Currently only argument supported is "lavc"'
complete -c tcdecode -s y -d 'target codec.   tcdecode  only decodes to raw format suitable for transcode'
complete -c tcdecode -s s -d 'audio gain for AC3 downmixing [1. 0,1. 0,1. 0]'
complete -c tcdecode -s Y -d 'decoded Digital Video (raw) YUV frame is in YUY2 (packet) format using libdv'
complete -c tcdecode -s A -d 'audio flag for AC3/A52 decoder [none]'
complete -c tcdecode -s Q -d 'decoding quality.  Certain codecs, e. g'
complete -c tcdecode -s d -d 'With this option you can specify a bitmask to enable different levels of verb…'
complete -c tcdecode -s v -d 'Print version information and exit'

