# tcdemux
# Autogenerated from man page /usr/lib/jvm/default/man/man1/tcdemux.1.gz
complete -c tcdemux -s i -d 'Specify input source.   If ommited, stdin is assumed. br'
complete -c tcdemux -s x -d 'Process only packets containing given  codec as payload'
complete -c tcdemux -s t -d 'Specify the input file type  magic.  Useful for using  tcdemux in pipelines'
complete -c tcdemux -s a -d 'Process only packets containing given audio track  ach and video track  vch'
complete -c tcdemux -s s -d 'Select specific multimedia track using the standard identifier  0xnn'
complete -c tcdemux -s f -d 'Specify the frame rate  fps for subtitle meta information used by external ap…'
complete -c tcdemux -s S -d 'Select a program unit  unit and a selected GOP range  s1-s2 for processing'
complete -c tcdemux -s O -d 'Do not skip initial sequence.  Used internally by transcode. br'
complete -c tcdemux -s A -d 'Select packets using an identifier for extracting only selected streams witho…'
complete -c tcdemux -s M -d 'Select synchronization strategy  mode'
complete -c tcdemux -s P -d 'Write GOP meta information to  file instead of \\fstdout. br'
complete -c tcdemux -s W -d 'Print a navigation log file for a given video stream to stdout'
complete -c tcdemux -s d -d 'With this option you can specify a bitmask to enable different levels of verb…'
complete -c tcdemux -s v -d 'Print version information and exit'

