# tcextract
# Autogenerated from man page /usr/lib/jvm/default/man/man1/tcextract.1.gz
complete -c tcextract -s i -d 'Specify input source.   If ommited, stdin is assumed'
complete -c tcextract -s C -d 'extract and print out only this frame interval (video) or bytes (audio) [all]'
complete -c tcextract -s t -d 'source file magic'
complete -c tcextract -s x -d 'source pdeudo-codec, if not detected when reading from stdin'
complete -c tcextract -s a -d 'extract selected audio or video track from source'
complete -c tcextract -s d -d 'With this option you can specify a bitmask to enable different levels of verb…'
complete -c tcextract -s v -d 'Print version information and exit'

