# tcexport
# Autogenerated from man page /usr/lib/jvm/default/man/man1/tcexport.1.gz
complete -c tcexport -s i -d 'Specify the path of video source'
complete -c tcexport -s p -d 'Specify the path of audio source'
complete -c tcexport -s o -d 'Specify the (base)path of output file'
complete -c tcexport -s c -d 'encode only frames f1-f2 [and f3-f4 and so on]'
complete -c tcexport -s N -d 'Setup the desired encoded video and audio format respectively'
complete -c tcexport -s R -d 'enable multi-pass encoding (0-3) [0,divx4. log,pcm. log]. RS'
complete -c tcexport -s P -d 'select export profile(s) to load'
complete -c tcexport -s y -d 'Select export modules: video and audio encoders, and multiplexor module'
complete -c tcexport -s w -d 'encoder bitrate[,keyframes[,crispness]] [(6000 for MPEG 1/2, 1800 for others)…'
complete -c tcexport -s b -d 'audio encoder bitrate kBits/s[,vbr[,quality[,mode]]] [128,0,5,0]'
complete -c tcexport -s D -d 'Select dry run mode: tcexport will probe stream, load selected modules then e…'
complete -c tcexport -s d -d 'Select the verbosity of program, support code and modules'
complete -c tcexport -s m -d 'Look in Path instead of the compiled-in module path for a module'
complete -c tcexport -s v -d 'Print version information and exit'

