# tcmodchain
# Autogenerated from man page /usr/lib/jvm/default/man/man1/tcmodchain.1.gz
complete -c tcmodchain -s m -d 'Look in Path instead of the compiled-in module path while trying to load a mo…'
complete -c tcmodchain -s C -d 'Enable check mode'
complete -c tcmodchain -s L -d 'Enable list mode'
complete -c tcmodchain -s d -d 'Specify the verbosiness level to use, like transcode does'
complete -c tcmodchain -s v -d 'Print version information and exit'

