# tcmodinfo
# Autogenerated from man page /usr/lib/jvm/default/man/man1/tcmodinfo.1.gz
complete -c tcmodinfo -s i -d 'Specify the name of the module.  Name is specified without the prefix  (i. e'
complete -c tcmodinfo -s m -d 'Look in Path instead of the compiled-in module path for a module'
complete -c tcmodinfo -s t -d 'Specify the Type of module to load.  Default is filter modules'
complete -c tcmodinfo -s M -d 'Print out the default setting of given parameter of a given (use -i/-t option…'
complete -c tcmodinfo -s C -d 'Request to configure the module using given configuration string'
complete -c tcmodinfo -s s -d 'Connect to socket socket'
complete -c tcmodinfo -s d -d 'Specify the verbosiness level to use, like transcode does'
complete -c tcmodinfo -s p -d 'Print the compiled-in module path and exit'
complete -c tcmodinfo -s v -d 'Print version information and exit.  EXAMPLES The command'

