# tcprobe
# Autogenerated from man page /usr/lib/jvm/default/man/man1/tcprobe.1.gz
complete -c tcprobe -s i -d 'Specify input source.   If ommited, stdin is assumed'
complete -c tcprobe -s B -d 'Binary output to stdout for use in transcode'
complete -c tcprobe -s M -d 'Use EXPERIMENTAL mplayer probe, useful for streams that tcprobe doesn\'t recog…'
complete -c tcprobe -s T -d 'Probe for DVD  title'
complete -c tcprobe -s H -d 'This option tells tcprobe to scan n MB of input data'
complete -c tcprobe -s s -d 'Skip the first n bytes of the input stream.  Default is to skip no bytes'
complete -c tcprobe -s b -d 'Set audio encoder bitrate to bitrate'
complete -c tcprobe -s f -d 'Read index/seek information from seekfile'
complete -c tcprobe -s d -d 'With this option you can specify a bitmask to enable different levels of verb…'
complete -c tcprobe -s v -d 'Print version information and exit'

