# tcpvmexportd
# Autogenerated from man page /usr/lib/jvm/default/man/man1/tcpvmexportd.1.gz
complete -c tcpvmexportd -s s -d 'Start tcpvmexportd in slave mode (internal use of export_pvm) [default]'
complete -c tcpvmexportd -s m -d 'Start tcpvmexportd in master mode [off]'
complete -c tcpvmexportd -s h -d 'Print help'
complete -c tcpvmexportd -s j -d 'Start merger process [off]'
complete -c tcpvmexportd -s L -d 'Create only the merge list [off]'
complete -c tcpvmexportd -s c -d 'Name of slave function req in slave mode [none]'
complete -c tcpvmexportd -s x -d 'Multiplex parameters [none]'
complete -c tcpvmexportd -s 1 -d 'First parameter to pass to the slave function [null]'
complete -c tcpvmexportd -s 2 -d 'Second parameter to pass to the slave function [null]'
complete -c tcpvmexportd -s 3 -d 'Third parameter to pass to the slave function [null]'
complete -c tcpvmexportd -s t -d 'Elab video or audio frame (video|audio|system|multisystem) [video]'
complete -c tcpvmexportd -s f -d 'Out file name [/tmp/my_file_name]'
complete -c tcpvmexportd -s p -d 'Multipass (0,1,2,3) [0]'
complete -c tcpvmexportd -s M -d 'Enable internal multipass [off]'
complete -c tcpvmexportd -s C -d 'Check the config or merge file [off]'
complete -c tcpvmexportd -s v -d 'Print the version.  EXAMPLES'

