# tcscan
# Autogenerated from man page /usr/lib/jvm/default/man/man1/tcscan.1.gz
complete -c tcscan -s i -d 'Specify input source.   If ommited, stdin is assumed'
complete -c tcscan -s d -d 'With this option you can specify a bitmask to enable different levels of verb…'
complete -c tcscan -s v -d 'Print version information and exit'

