# tcxmlcheck
# Autogenerated from man page /usr/lib/jvm/default/man/man1/tcxmlcheck.1.gz
complete -c tcxmlcheck -s i -d 'Specify the name of the input video/audio smil file [stdin]'
complete -c tcxmlcheck -s p -d 'Specify the name of the ausiliary audio smil file [none]'
complete -c tcxmlcheck -s B -d 'Binary output to stdout (used by transcode) [off] Force to print to stdout th…'
complete -c tcxmlcheck -s S -d 'Write stdin into shared memory (used by transcode)[off]'
complete -c tcxmlcheck -s V -d 'Check only video smil file [off]'
complete -c tcxmlcheck -s A -d 'Check only ausiliary audio smil file [off]'
complete -c tcxmlcheck -s v -d 'Print the version EXAMPLES'

