# termsaver
# Autogenerated from man page /usr/share/man/man1/termsaver.1.gz
complete -c termsaver -s v -l verbose -d 'Displays python exception errors (for debugging)'
complete -c termsaver -l word -l delay

