# tiffcrop
# Autogenerated from man page /usr/share/man/man1/tiffcrop.1.gz
complete -c tiffcrop -s 1 -d 'it will results in infinite number of the rows per strip'
complete -c tiffcrop -s D -d 'Display program progress and/or dump raw data to non-TIFF files'

