# twm
# Autogenerated from man page /usr/lib/jvm/default/man/man1/twm.1.gz
complete -c twm -o display -d 'This option specifies the X server to use'
complete -c twm -s s -d 'This option indicates that only the default screen (as specified by -display …'
complete -c twm -s f -d 'This option specifies the name of the startup file to use'
complete -c twm -s v -d 'This option indicates that twm should print error messages whenever an unexpe…'

