# usbredirserver
# Autogenerated from man page /usr/lib/jvm/default/man/man1/usbredirserver.1.gz
complete -c usbredirserver -s p -l port -d 'Set the TCP port to listen on to PORT'
complete -c usbredirserver -s v -l verbose -d 'Set usbredirserver\'s verbosity level to VERBOSE, this mostly affects USB redi…'

