# vfstest
# Autogenerated from man page /usr/lib/jvm/default/man/man1/vfstest.1.gz
complete -c vfstest -s c -l command -d 'Execute the specified (semicolon-separated) commands'
complete -c vfstest -s '?' -l help -d 'Print a summary of command line options'
complete -c vfstest -s l -l logfile -d 'File name for log/debug files.  The extension \\*(Aq'
complete -c vfstest -s d -l debuglevel -d 'level is an integer from 0 to 10'
complete -c vfstest -s V -l version -d 'Prints the program version number'
complete -c vfstest -s s -l configfile -d 'The file specified contains the configuration details required by the server'
complete -c vfstest -l log-basename -d 'Base directory name for log/debug files.  The extension "'
complete -c vfstest -l option -d 'Set the smb. conf(5) option "<name>" to value "<value>" from the command line'

