# voikkospell
# Autogenerated from man page /usr/lib/jvm/default/man/man1/voikkospell.1.gz
complete -c voikkospell -s m -d 'In addition to spelling result, prints morphological analysis info (A:) for r…'
complete -c voikkospell -s M -d 'Prints morphological analysis info (A:) for recognized words without displayi…'
complete -c voikkospell -s t -d 'Prints only "C" or "W" instead of typical full output'
complete -c voikkospell -o tt -d 'Prints only misspelled words'
complete -c voikkospell -s s -d 'Prints suggestions (S:) for incorrectly spelled words'
complete -c voikkospell -s c -d 'Set cache size parameter to R n .  -1 disables the cache and 0 is the default'
complete -c voikkospell -s j -d 'Use  n threads for spell checking'
complete -c voikkospell -s x -d 'Like  voikkospell -s but output is printed on one line separated by character…'
complete -c voikkospell -s l -d 'Prints a list of available dictionary variants and exits'
complete -c voikkospell -s L -d 'Prints a list of capabilities and languages for which these capabilities are …'
complete -c voikkospell -s 1 -d 'For checking large amounts of unsorted text you may want to set n to 5 to get…'
complete -c voikkospell -s p -d '(voikkospell, voikkohyphenate, voikkogc) Look from directory before the stand…'
complete -c voikkospell -s d -d '(voikkospell, voikkohyphenate, voikkogc) Use dictionary variant variant inste…'
complete -c voikkospell -s h -l help -d 'Print a help message and exit'
complete -c voikkospell -l version -d 'Print version numbers for libvoikko and the test tool'

