# voikkogc
# Autogenerated from man page /usr/lib/jvm/default/man/man1/voikkogc.1.gz
complete -c voikkogc -l tokenize -d 'Instead of looking for grammar errors, split input into tokens'
complete -c voikkogc -l split-sentences -d 'Instead of looking for grammar errors, split input into sentences'
complete -c voikkogc -s n -d 'Prefix all grammar checker messages with line number of input data'

