# winbindd
# Autogenerated from man page /usr/lib/jvm/default/man/man8/winbindd.8.gz
complete -c winbindd -s D -l daemon -d 'If specified, this parameter causes the server to operate as a daemon'
complete -c winbindd -s F -l foreground -d 'If specified, this parameter causes the main winbindd process to not daemoniz…'
complete -c winbindd -s S -l stdout -d 'If specified, this parameter causes winbindd to log to standard output rather…'
complete -c winbindd -s d -l debuglevel -d 'level is an integer from 0 to 10'
complete -c winbindd -s V -l version -d 'Prints the program version number'
complete -c winbindd -s s -l configfile -d 'The file specified contains the configuration details required by the server'
complete -c winbindd -s l -l log-basename -d 'Base directory name for log/debug files.  The extension "'
complete -c winbindd -l option -d 'Set the smb. conf(5) option "<name>" to value "<value>" from the command line'
complete -c winbindd -s '?' -l help -d 'Print a summary of command line options'
complete -c winbindd -l usage -d 'Display brief usage message'
complete -c winbindd -s i -l interactive -d 'Tells winbindd to not become a daemon and detach from the current terminal'
complete -c winbindd -s n -l no-caching -d 'Disable some caching'
complete -c winbindd -l no-process-group -d 'Do not create a new process group for winbindd'
complete -c winbindd -s U -d 'can be any Domain user that has administrator privileges on the machine'
complete -c winbindd -l with-lockdir -d 'option.  This directory is by default /usr/local/samba/var/locks'

