# winetricks
# Autogenerated from man page /usr/lib/jvm/default/man/man1/winetricks.1.gz
complete -c winetricks -l country -d 'Set country code to CC and don\'t detect your IP address when retrying downloa…'
complete -c winetricks -l force -d 'Don\'t check whether packages were already installed'
complete -c winetricks -l gui -d 'Show GUI diagnostics even when driven by the command-line interface'
complete -c winetricks -l isolate -d 'Install each app or game in its own bottle'
complete -c winetricks -s k -l keep_isos -d 'Cache ISOs (allows later installation without disc)'
complete -c winetricks -l no-isolate -d 'Don\'t install each app or game in its own bottle (default)'
complete -c winetricks -l no-clean -d 'Don\'t delete temp directories (useful during debugging)'
complete -c winetricks -s q -l unattended -d 'Don\'t ask any questions, just install automatically'
complete -c winetricks -s r -l ddrescue -d 'Retry hard when caching scratched discs'
complete -c winetricks -s v -l verbose -d 'Echo all commands as they are executed'
complete -c winetricks -s h -l help -d 'Display this message and exit'
complete -c winetricks -s V -l version -d 'Display version and exit'

