# winedump
# Autogenerated from man page /usr/lib/jvm/default/man/man1/winedump.1.gz
complete -c winedump -s C -d 'Turns on symbol demangling'
complete -c winedump -s f -d 'Dumps file header information'
complete -c winedump -s j -d 'Dumps only the content of directory dir_name, for files which header points t…'
complete -c winedump -s x -d 'Dumps everything'
complete -c winedump -s G -d 'Dumps contents of debug section if any (for now, only stabs information is su…'
complete -c winedump -s I -d 'Look for prototypes in dir (implies -c)'
complete -c winedump -s c -d 'Generate skeleton code (requires -I)'
complete -c winedump -s t -d 'TRACE arguments (implies -c)'
complete -c winedump -s D -d 'Generate documentation'
complete -c winedump -s o -d 'Set the output dll name (default: dll)'
complete -c winedump -s s -d 'Start prototype search after symbol num'
complete -c winedump -s e -d 'End prototype search after symbol num'
complete -c winedump -s S -d 'Search only prototype names found in symfile'
complete -c winedump -s q -d 'Don\'t show progress (quiet)'
complete -c winedump -s v -d 'Show lots of detail while working (verbose)'
complete -c winedump -s h -d 'Help mode.  Basic usage help is printed.  dump To dump the contents of a file'

