# wmc
# Autogenerated from man page /usr/lib/jvm/default/man/man1/wmc.1.gz
complete -c wmc -s B -d 'Set output byte-order x={n[ative], l[ittle], b[ig]}.  Default is n[ative]'
complete -c wmc -s c -d 'Set \'custom-bit\' in message-code values'
complete -c wmc -s d -d 'NON-FUNCTIONAL; Use decimal values in output'
complete -c wmc -s D -d 'Set debug flag.  This results is a parser trace and a lot of extra messages'
complete -c wmc -s h -l help -d 'Print an informative usage message and exits'
complete -c wmc -s H -d 'Write headerfile to file.  Default is inputfile. h'
complete -c wmc -s i -d 'Inline messagetable(s).  This option skips the generation of all '
complete -c wmc -l nls-dir -d 'Specify the directory to search for the NLS files containing the codepage map…'
complete -c wmc -s o -l output -d 'Output to file.  Default is inputfile. rc'
complete -c wmc -s O -l output-format -d 'Set the output format.  Supported formats are rc (the default), res, and pot'
complete -c wmc -s P -l po-dir -d 'Enable the generation of resource translations based on po files loaded from …'
complete -c wmc -s u -d 'Assume that the input file is in Unicode or UTF-8 format and skip codepage co…'
complete -c wmc -s v -d 'Show all supported codepages and languages'
complete -c wmc -s V -l version -d 'Print version end exit'
complete -c wmc -s W -l pedantic -d 'Enable pedantic warnings'

