# xwinfo
# Autogenerated from man page /usr/lib/jvm/default/man/man1/xwinfo.1.gz
complete -c xwinfo -s h -d 'Print the synopsis to standard output and exit'
complete -c xwinfo -s v -d 'Print the version information to standard output and exit'
complete -c xwinfo -s c -d 'Print the class name'
complete -c xwinfo -s i -d 'Print the instance name'
complete -c xwinfo -s n -d 'Print the window title'
complete -c xwinfo -s t -d 'Print the window type'
complete -c xwinfo -s s -d 'Print the window state'
complete -c xwinfo -s g -d 'Print the geometry (as width height x y)'

