# y4munsharp
# Autogenerated from man page /usr/share/man/man1/y4munsharp.1.gz
complete -c y4munsharp -s C -d 'CbCr (chroma) unsharp parameters'
complete -c y4munsharp -s N -d 'Filtering can produce output outside the 16 to 240 range for Y\' and 16 to 235…'

