#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        1 
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

bspc rule -a ./$HOME/Documents/autostart-scripts/firefox.sh desktop='^2'
bspc rule -a Spotify desktop='^10'

picom -f &
./.config/polybar/launch.sh
nitrogen --restore &
ckb-next --background
pulseeffects --gapplication-service
